const List<Map<String, String>> trainingData = [
  // STRESS / BURNED OUT
  {'text': 'capek banget kerjaan gak kelar', 'label': 'stress'},
  {'text': 'pusing tugas numpuk', 'label': 'stress'},
  {'text': 'mau gila rasanya deadline mepet', 'label': 'stress'},
  {'text': 'burnout parah', 'label': 'stress'},
  {'text': 'stress berat kantor toxic', 'label': 'stress'},
  {'text': 'lelah jiwa raga', 'label': 'stress'},
  {'text': 'pengen resign aja', 'label': 'stress'},
  {'text': 'anxiety kambuh lagi', 'label': 'stress'},
  {'text': 'overthinking mulu malem ini', 'label': 'stress'},
  {'text': 'beban hidup berat banget', 'label': 'stress'},
  {'text': 'otak ngebul', 'label': 'stress'},
  {'text': 'gak kuat lagi', 'label': 'stress'},
  {'text': 'tekanan batin', 'label': 'stress'},
  {'text': 'muak sama semuanya', 'label': 'stress'},
  {'text': 'stress', 'label': 'stress'},
  {'text': 'overthinking mulu', 'label': 'stress'},
  {'text': 'fomo liat temen jalan jalan', 'label': 'stress'},
  {'text': 'takut ketinggalan', 'label': 'stress'},
  {'text': 'ribet banget idup', 'label': 'stress'},
  {'text': 'banyak pikiran', 'label': 'stress'},
  {'text': 'pusing mikirin duit', 'label': 'stress'},
  {'text': 'deg degan parah', 'label': 'stress'},
  {'text': 'panik gak jelas', 'label': 'stress'},
  {'text': 'burnout kerjaan', 'label': 'stress'},
  {'text': 'kena mental', 'label': 'stress'},
  {'text': 'toxic banget lingkungan sini', 'label': 'stress'},
  {'text': 'gaslighting mulu', 'label': 'stress'},
  {'text': 'overthinking mulu', 'label': 'stress'},
  {'text': 'fomo liat temen jalan jalan', 'label': 'stress'},
  {'text': 'takut ketinggalan', 'label': 'stress'},
  {'text': 'ribet banget idup', 'label': 'stress'},
  {'text': 'banyak pikiran', 'label': 'stress'},
  {'text': 'pusing mikirin duit', 'label': 'stress'},
  {'text': 'deg degan parah', 'label': 'stress'},
  {'text': 'panik gak jelas', 'label': 'stress'},
  {'text': 'burnout kerjaan', 'label': 'stress'},
  {'text': 'kena mental', 'label': 'stress'},
  {'text': 'toxic banget lingkungan sini', 'label': 'stress'},
  {'text': 'gaslighting mulu', 'label': 'stress'},

  // SAD / DEPRESSED
  {'text': 'sedih banget hari ini', 'label': 'sad'},
  {'text': 'pengen nangis aja', 'label': 'sad'},
  {'text': 'kesepian gak ada temen', 'label': 'sad'},
  {'text': 'insecure liat orang lain', 'label': 'sad'},
  {'text': 'ngerasa gagal terus', 'label': 'sad'},
  {'text': 'gak pede', 'label': 'sad'},
  {'text': 'hati hancur', 'label': 'sad'},
  {'text': 'galau berat', 'label': 'sad'},
  {'text': 'bad mood parah', 'label': 'sad'},
  {'text': 'gak ada yang ngerti', 'label': 'sad'},
  {'text': 'sendirian lagi', 'label': 'sad'},
  {'text': 'capek batin', 'label': 'sad'},
  {'text': 'insecure liat orang lain', 'label': 'sad'},
  {'text': 'ngerasa gagal terus', 'label': 'sad'},
  {'text': 'gak pede', 'label': 'sad'},
  {'text': 'hati hancur', 'label': 'sad'},
  {'text': 'galau berat', 'label': 'sad'},
  {'text': 'bad mood parah', 'label': 'sad'},
  {'text': 'gak ada yang ngerti', 'label': 'sad'},
  {'text': 'sendirian lagi', 'label': 'sad'},

  // HAPPY / EXCITED
  {'text': 'seneng banget akhirnya kelar', 'label': 'happy'},
  {'text': 'bahagia hari ini', 'label': 'happy'},
  {'text': 'healing dulu bos', 'label': 'happy'},
  {'text': 'self reward nih', 'label': 'happy'},
  {'text': 'mantap jiwa', 'label': 'happy'},
  {'text': 'alhamdulillah rejeki', 'label': 'happy'},
  {'text': 'seru banget tadi', 'label': 'happy'},
  {'text': 'asyik', 'label': 'happy'},
  {'text': 'mood booster', 'label': 'happy'},
  {'text': 'semangat 45', 'label': 'happy'},
  {'text': 'keren abis', 'label': 'happy'},
  {'text': 'gokil', 'label': 'happy'},
  {'text': 'healing dulu bos', 'label': 'happy'},
  {'text': 'self reward nih', 'label': 'happy'},
  {'text': 'alhamdulillah rejeki', 'label': 'happy'},
  {'text': 'seru banget tadi', 'label': 'happy'},
  {'text': 'mood booster', 'label': 'happy'},
  {'text': 'semangat 45', 'label': 'happy'},
  {'text': 'keren abis', 'label': 'happy'},

  // NEUTRAL / CASUAL
  {'text': 'halo jedo', 'label': 'neutral'},
  {'text': 'lagi apa bro', 'label': 'neutral'},
  {'text': 'tes tes 123', 'label': 'neutral'},
  {'text': 'gabut nih', 'label': 'neutral'},
  {'text': 'bingung mau ngapain', 'label': 'neutral'},
  {'text': 'rekomendasi lagu dong', 'label': 'neutral'},
  {'text': 'cuaca panas ya', 'label': 'neutral'},
  {'text': 'laper', 'label': 'neutral'},
  {'text': 'ngantuk', 'label': 'neutral'},
  {'text': 'oke sip', 'label': 'neutral'},
  {'text': 'yoi', 'label': 'neutral'},
  {'text': 'siap', 'label': 'neutral'},
];
